//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrizeDrawSystem.POSMachineUserChancesReport {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class POSMachineUserChancesReport {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(POSMachineUserChancesReport target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::PrizeDrawSystem.POSMachineUserChancesReport.POSMachineUserChancesReport @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h2 class=\"text-c" +
                        "enter mt-5\">Users Chances Report (POS Machine)</h2>\r\n        <hr class=\"mb-5\">\r\n" +
                        "\r\n        <div class=\"dropdown\">\r\n            <button type=\"button\" class=\"btn b" +
                        "tn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n                Select Repo" +
                        "rt To View\r\n            </button>\r\n            <div class=\"dropdown-menu\">\r\n    " +
                        "            <a class=\"dropdown-item\" href=\"javascript:;\" onclick=\"LoadReport(\'We" +
                        "ekly\')\">Weekly</a>\r\n                <a class=\"dropdown-item\" href=\"javascript:;\"" +
                        " onclick=\"LoadReport(\'Monthly\')\">Monthly</a>\r\n                <a class=\"dropdown" +
                        "-item\" href=\"javascript:;\" onclick=\"LoadReport(\'Quarterly\')\">Quarterly</a>\r\n    " +
                        "            <a class=\"dropdown-item\" href=\"javascript:;\" onclick=\"LoadReport(\'Ha" +
                        "lf Yearly\')\">Half Yearly</a>\r\n                <a class=\"dropdown-item\" href=\"jav" +
                        "ascript:;\" onclick=\"LoadReport(\'Yearly\')\">Yearly</a>\r\n                <a class=\"" +
                        "dropdown-item\" href=\"javascript:;\" onclick=\"LoadReport(\'One Time\')\">One Time</a>" +
                        "\r\n            </div>\r\n        </div>\r\n\r\n        <div id=\"winnersDiv\" style=\"disp" +
                        "lay: none;\">\r\n            <h2 class=\"winnersHeading\">Users Chances\r\n            " +
                        "</h2>\r\n            <table id=\"reportTbl\" class=\"display\" style=\"width: 100%;\">\r\n" +
                        "                <thead>\r\n                    <tr>\r\n                        <th>C" +
                        "ustomer Name</th>\r\n                        <th>Account No</th>\r\n                " +
                        "        <th>Credit Card No</th>\r\n                        <th>Branch Code</th>\r\n " +
                        "                       <th>Chances To Win</th>\r\n                    </tr>\r\n     " +
                        "           </thead>\r\n            </table>\r\n\r\n        </div>\r\n\r\n    </div>\r\n</div" +
                        ">\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    var winners = [];\r\n\r\n    function Lo" +
                        "adReport(reportType) {\r\n\r\n        var methodUrl = [location.protocol, \'//\', loca" +
                        "tion.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.aspx/GetPOSMachineUse" +
                        "rsChancesReport\';\r\n        $(\'.winnersHeading\').html(\'Users Chances (\' + reportT" +
                        "ype + \')\');\r\n        $(\'.ajax-loader\').css(\"visibility\", \"visible\");\r\n\r\n        " +
                        "$.ajax({\r\n            type: \"POST\",\r\n            url: methodUrl,\r\n            da" +
                        "ta: JSON.stringify({ reportType: reportType }),\r\n            contentType: \"appli" +
                        "cation/json; charset=utf-8\",\r\n            dataType: \"json\",\r\n            success" +
                        ": function (result) {\r\n\r\n                $(\'.ajax-loader\').css(\"visibility\", \"hi" +
                        "dden\");\r\n\r\n                if (result != null && result.d != null && result.d.le" +
                        "ngth > 0) {\r\n\r\n                    winners = result.d;\r\n\r\n                    va" +
                        "r table = $(\'#reportTbl\').DataTable();\r\n                    table.destroy();\r\n\r\n" +
                        "                    $(\'#reportTbl\').DataTable({\r\n                        data: w" +
                        "inners,\r\n                        columns: [\r\n                            { \"data" +
                        "\": \"CustomerName\" },\r\n                            { \"data\": \"AccountNumber\" },\r\n" +
                        "                            { \"data\": \"CreditCardNumber\" },\r\n                   " +
                        "         { \"data\": \"BranchCode\" },\r\n                            { \"data\": \"Chanc" +
                        "es\" }\r\n                        ]\r\n                    });\r\n\r\n                   " +
                        " $(\"#winnersDiv\").fadeIn(2000);\r\n\r\n\r\n\r\n                }\r\n\r\n            },\r\n    " +
                        "        error: function (jqXHR, textStatus, errorThrown) {\r\n                cons" +
                        "ole.log(\'Error occured\');\r\n                $(\'.ajax-loader\').css(\"visibility\", \"" +
                        "hidden\");\r\n\r\n                if (jqXHR.status == 500) {\r\n                    con" +
                        "sole.log(\'Internal error: \' + jqXHR.responseText);\r\n                } else {\r\n  " +
                        "                  console.log(\'Unexpected error.\');\r\n                }\r\n        " +
                        "    }\r\n        });\r\n    }\r\n\r\n    $(function () {\r\n\r\n        //LoadReport();\r\n   " +
                        " });\r\n\r\n</script>\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
