//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrizeDrawSystem.POSMachinePrizeDraw {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class POSMachinePrizeDraw {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(POSMachinePrizeDraw target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::PrizeDrawSystem.POSMachinePrizeDraw.POSMachinePrizeDraw @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n\r\n<div class=\"row\">\r\n\t<div class=\"col-md-12\">\r\n\t\t<h2 class=\"text-center mt-5\"" +
                    ">\r\n            ");
    @__w.Write(DrawType );

            @__w.Write(" Draw (Credit Card Draw)\r\n            <br />\r\n            السحب لمرة واحدة (سحب ا" +
                    "لبطاقة الائتمانية)\r\n\t\t</h2>\r\n\t\t<hr class=\"mb-5\">\r\n\t\t\r\n\t\t<div class=\"row\" id=\"loa" +
                    "dingGifRow\">\r\n\t\t\r\n\t\t\t<div class=\"col-md-3\">\r\n\t\t\t\t\r\n\t\t\t</div>\r\n\t\t\t\r\n\t\t\t<div class" +
                    "=\"col-md-6 text-center\">\r\n\t\t\t\t<img src=\"/PublishingImages/Icons/loading.gif\" id=" +
                    "\"loadingGif\" style=\"display: none; width: 80%;\"/>\r\n\t\t\t\t<div class=\"startDrawDiv\"" +
                    ">\r\n\t\t\t\t\t<button class=\"startDrawBtn\" onclick=\"return false;\">Start Draw بدء السح" +
                    "ب</button>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\r\n\t\t\t<div class=\"col-md-3\">\r\n\t\t\t\t\r\n\t\t\t</div>\r" +
                    "\n\r\n\t\t\r\n\t\t</div>\r\n\t\t\r\n\t\t<div id=\"winnersDiv\"  style=\"display: none;\">\r\n\t\t\t<h2 cla" +
                    "ss=\"winnersHeading\">\r\n\t\t\t\tWinners\r\n                <br />\r\n                الفائ" +
                    "زين\r\n\t\t\t</h2>\r\n\t\t\t<table id=\"winnersTbl\" class=\"display\" style=\"width: 100%;\">\r\n" +
                    "\t\t\t\t<thead>\r\n\t\t            <tr>\r\n\t\t                <th>Customer Name <br /> إسم " +
                    "العميل</th>\r\n\t\t                <th>Account No <br /> رقم الحساب</th>\r\n          " +
                    "              <th>Credit Card No <br /> رقم البطاقة الائتمانية</th>\r\n           " +
                    "             <th>Branch Code <br /> رمز الفرع</th>\r\n                        <th>" +
                    "Winning Amount <br />قيمة الجائزة</th>\r\n\t\t            </tr>\r\n\t\t        </thead>\r" +
                    "\n\t\t\t</table>\r\n\t\t\t<div class=\"row\" style=\"margin-top: 25px; display: none;\" id=\"s" +
                    "aveResultsRow\">\r\n                <div class=\"col text-center\">\r\n                " +
                    "  <button class=\"btn btn-primary\" onclick=\"SaveWinnerResults(); return false;\">S" +
                    "ave Results</button>\r\n                </div>\r\n            </div>\r\n\t\t</div>\r\n\t\t\r\n" +
                    "\t</div>\r\n</div>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    var maxWinners = 0;\r\n " +
                    "   var winners = [];\r\n\r\n    function LoadConfigurations() {\r\n\r\n        $(\'.ajax-" +
                    "loader\').css(\"visibility\", \"visible\");\r\n\r\n        var methodUrl = [location.prot" +
                    "ocol, \'//\', location.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.aspx/" +
                    "GetDrawButtonStatus\';\r\n        $.ajax({\r\n            type: \"POST\",\r\n            " +
                    "url: methodUrl,\r\n            data: JSON.stringify({ drawCategory: \"POS Machine\" " +
                    "}),\r\n            contentType: \"application/json; charset=utf-8\",\r\n            da" +
                    "taType: \"json\",\r\n            success: function (result) {\r\n\r\n                $(\'" +
                    ".ajax-loader\').css(\"visibility\", \"hidden\");\r\n\r\n                if (result != nul" +
                    "l && result.d != null) {\r\n\r\n                    if (result.d == false) {\r\n\r\n    " +
                    "                    var html = \'\';\r\n                        html += \'<div class=" +
                    "\"toast\" data-autohide=\"false\" style=\"max-width: 100%;\">\';\r\n                     " +
                    "   html += \'<div class=\"toast-header\">\';\r\n                        html += \'<stro" +
                    "ng class=\"mr-auto text-primary\" id=\"msgHdr\">Message</strong>\';\r\n                " +
                    "        html += \'<button type=\"button\" class=\"ml-2 mb-1 close\" data-dismiss=\"toa" +
                    "st\">&times;</button>\';\r\n                        html += \'</div>\';\r\n             " +
                    "           html += \'<div class=\"toast-body\" id=\"msgBody\">\';\r\n                   " +
                    "     html += \'Please Import Data to start draw\';\r\n                        html +" +
                    "= \'</div>\';\r\n                        html += \'</div>\';\r\n\r\n                      " +
                    "  $(\'.startDrawDiv\').html(html);\r\n                        $(\'.toast\').toast(\'sho" +
                    "w\');\r\n                    }\r\n                    else {\r\n                       " +
                    " LoadDrawConfigurations();\r\n                    }\r\n                }\r\n\r\n        " +
                    "    },\r\n            error: function (jqXHR, textStatus, errorThrown) {\r\n        " +
                    "        console.log(\'Error occured\');\r\n                $(\'.ajax-loader\').css(\"vi" +
                    "sibility\", \"hidden\");\r\n\r\n                if (jqXHR.status == 500) {\r\n           " +
                    "         console.log(\'Internal error: \' + jqXHR.responseText);\r\n                " +
                    "} else {\r\n                    console.log(\'Unexpected error.\');\r\n               " +
                    " }\r\n            }\r\n        });\r\n    }\r\n\r\n    function LoadDrawConfigurations() {" +
                    "\r\n\r\n        $(\'.ajax-loader\').css(\"visibility\", \"visible\");\r\n\r\n        var metho" +
                    "dUrl = [location.protocol, \'//\', location.host].join(\'\') + \'/_layouts/15/PrizeDr" +
                    "awSystem/WebAPI.aspx/GetMaxPOSMachineWinners\';\r\n        $.ajax({\r\n            ty" +
                    "pe: \"POST\",\r\n            url: methodUrl,\r\n            data: JSON.stringify({}),\r" +
                    "\n            contentType: \"application/json; charset=utf-8\",\r\n            dataTy" +
                    "pe: \"json\",\r\n            success: function (result) {\r\n\r\n                $(\'.aja" +
                    "x-loader\').css(\"visibility\", \"hidden\");\r\n\r\n                if (result != null &&" +
                    " result.d != null) {\r\n\r\n                    maxWinners = result.d;\r\n            " +
                    "    }\r\n\r\n            },\r\n            error: function (jqXHR, textStatus, errorTh" +
                    "rown) {\r\n                console.log(\'Error occured\');\r\n                $(\'.ajax" +
                    "-loader\').css(\"visibility\", \"hidden\");\r\n\r\n                if (jqXHR.status == 50" +
                    "0) {\r\n                    console.log(\'Internal error: \' + jqXHR.responseText);\r" +
                    "\n                } else {\r\n                    console.log(\'Unexpected error.\');" +
                    "\r\n                }\r\n            }\r\n        });\r\n    }\r\n\r\n    function DeleteAnd" +
                    "ArchiveData() {\r\n\r\n        var methodUrl = [location.protocol, \'//\', location.ho" +
                    "st].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.aspx/ArchiveAndDeletePOSMach" +
                    "ineData\';\r\n        $.ajax({\r\n            type: \"POST\",\r\n            url: methodU" +
                    "rl,\r\n            data: JSON.stringify({}),\r\n            contentType: \"applicatio" +
                    "n/json; charset=utf-8\",\r\n            dataType: \"json\",\r\n            success: fun" +
                    "ction (result) {\r\n\r\n            },\r\n            error: function (jqXHR, textStat" +
                    "us, errorThrown) {\r\n                alert(\'Error occured\');\r\n                if " +
                    "(jqXHR.status == 500) {\r\n                    console.log(\'Internal error: \' + jq" +
                    "XHR.responseText);\r\n                } else {\r\n                    console.log(\'U" +
                    "nexpected error.\');\r\n                }\r\n            }\r\n        });\r\n    }\r\n\r\n   " +
                    " function SaveWinnerResults() {\r\n\r\n        if (winners != null && winners.length" +
                    " > 0) {\r\n\r\n            for (var i = 0; i < winners.length; i++) {\r\n\r\n           " +
                    "     winners[i].TransactionDate = new Date(parseInt(winners[i].TransactionDate.s" +
                    "ubstr(6))).toJSON();\r\n                delete winners[i].__type;\r\n            }\r\n" +
                    "\r\n            var methodUrl = [location.protocol, \'//\', location.host].join(\'\') " +
                    "+ \'/_layouts/15/PrizeDrawSystem/WebAPI.aspx/SavePOSMachineWinners\';\r\n           " +
                    " $(\'.ajax-loader\').css(\"visibility\", \"visible\");\r\n\r\n            $.ajax({\r\n      " +
                    "          type: \"POST\",\r\n                url: methodUrl,\r\n                data: " +
                    "JSON.stringify({ drawType: \"");
                                          @__w.Write(DrawType);

            @__w.Write("\", allWinners: winners }),\r\n                contentType: \"application/json; chars" +
                    "et=utf-8\",\r\n                dataType: \"json\",\r\n                success: function" +
                    " (result) {\r\n\r\n                    $(\'.ajax-loader\').css(\"visibility\", \"hidden\")" +
                    ";\r\n\r\n                    console.log(result);\r\n                    if (result !=" +
                    " null && result.d != null) {\r\n\r\n                        DeleteAndArchiveData();\r" +
                    "\n\r\n                        var html = \'\';\r\n                        html += \'<div" +
                    " class=\"toast\" data-autohide=\"false\" style=\"max-width: 100%;\">\';\r\n              " +
                    "          html += \'<div class=\"toast-header\">\';\r\n                        html +=" +
                    " \'<strong class=\"mr-auto text-primary\" id=\"msgHdr\">Message</strong>\';\r\n         " +
                    "               html += \'<button type=\"button\" class=\"ml-2 mb-1 close\" data-dismi" +
                    "ss=\"toast\">&times;</button>\';\r\n                        html += \'</div>\';\r\n      " +
                    "                  html += \'<div class=\"toast-body\" id=\"msgBody\">\';\r\n            " +
                    "            html += \'Winners data is saved successfully\';\r\n                     " +
                    "   html += \'</div>\';\r\n                        html += \'</div>\';\r\n\r\n             " +
                    "           $(\'.startDrawDiv\').html(html);\r\n                        $(\'.toast\').t" +
                    "oast(\'show\');\r\n                        $(\'#loadingGifRow\').show();\r\n            " +
                    "            $(\'#winnersDiv\').html(\'\');\r\n                    }\r\n\r\n               " +
                    " },\r\n                error: function (jqXHR, textStatus, errorThrown) {\r\n       " +
                    "             console.log(\'Error occured\');\r\n                    $(\'.ajax-loader\'" +
                    ").css(\"visibility\", \"hidden\");\r\n\r\n                    if (jqXHR.status == 500) {" +
                    "\r\n                        console.log(\'Internal error: \' + jqXHR.responseText);\r" +
                    "\n                    } else {\r\n                        console.log(\'Unexpected e" +
                    "rror.\');\r\n                    }\r\n                }\r\n            });\r\n        }\r\n" +
                    "    }\r\n\r\n    $(function () {\r\n\r\n        \r\n        LoadConfigurations();\r\n\r\n     " +
                    "   $(\'.startDrawBtn\').click(function () {\r\n\r\n            $(\'.startDrawBtn\').hide" +
                    "();\r\n            $(\"#loadingGif\").fadeIn(2000);\r\n\r\n            \r\n            var" +
                    " methodUrl = [location.protocol, \'//\', location.host].join(\'\') + \'/_layouts/15/P" +
                    "rizeDrawSystem/WebAPI.aspx/\';\r\n\r\n            if (maxWinners > 5) {\r\n\r\n          " +
                    "      methodUrl += \"GetPOSMachineAllWinners\";\r\n                $(\'.ajax-loader\')" +
                    ".css(\"visibility\", \"visible\");\r\n\r\n                $.ajax({\r\n                    " +
                    "type: \"POST\",\r\n                    url: methodUrl,\r\n                    data: JS" +
                    "ON.stringify({ drawType: \"");
                                              @__w.Write(DrawType);

            @__w.Write("\" }),\r\n                    contentType: \"application/json; charset=utf-8\",\r\n     " +
                    "               dataType: \"json\",\r\n                    success: function (result)" +
                    " {\r\n\r\n                        $(\'.ajax-loader\').css(\"visibility\", \"hidden\");\r\n\r\n" +
                    "                        if (result != null && result.d != null && result.d.lengt" +
                    "h > 0) {\r\n\r\n                            winners = result.d;\r\n\r\n                 " +
                    "           setTimeout(function () {\r\n\r\n                                $(\'#winne" +
                    "rsTbl\').DataTable({\r\n                                    data: winners,\r\n       " +
                    "                             \"bSort\": false,\r\n                                  " +
                    "  columns: [\r\n                                        { \"data\": \"CustomerName\" }" +
                    ",\r\n                                        { \"data\": \"AccountNumber\" },\r\n       " +
                    "                                 { \"data\": \"CreditCardNumber\" },\r\n              " +
                    "                          { \"data\": \"BranchCode\" },\r\n                           " +
                    "             { \"data\": \"WinningAmount\" }\r\n                                    ]\r" +
                    "\n                                });\r\n\r\n                                $(\"#load" +
                    "ingGif\").fadeOut(2000);\r\n                                $(\'#loadingGifRow\').hid" +
                    "e();\r\n                                $(\"#winnersDiv\").fadeIn(2000);\r\n          " +
                    "                      $(\"#saveResultsRow\").fadeIn(2000);\r\n\r\n                    " +
                    "        }, 3000);\r\n\r\n\r\n\r\n                        }\r\n\r\n                    },\r\n  " +
                    "                  error: function (jqXHR, textStatus, errorThrown) {\r\n          " +
                    "              console.log(\'Error occured\');\r\n                        $(\'.ajax-lo" +
                    "ader\').css(\"visibility\", \"hidden\");\r\n\r\n                        if (jqXHR.status " +
                    "== 500) {\r\n                            console.log(\'Internal error: \' + jqXHR.re" +
                    "sponseText);\r\n                        } else {\r\n                            cons" +
                    "ole.log(\'Unexpected error.\');\r\n                        }\r\n                    }\r" +
                    "\n                });\r\n            }\r\n            else {\r\n\r\n                metho" +
                    "dUrl += \"GetPOSMachineSingleWinner\";\r\n\r\n                if (winners != null && w" +
                    "inners.length > 0) {\r\n\r\n                    for (var i = 0; i < winners.length; " +
                    "i++) {\r\n\r\n                        winners[i].TransactionDate = new Date(parseInt" +
                    "(winners[i].TransactionDate.substr(6))).toJSON();\r\n                        delet" +
                    "e winners[i].__type;\r\n                    }\r\n                }\r\n\r\n              " +
                    "  $(\'.ajax-loader\').css(\"visibility\", \"visible\");\r\n\r\n                $.ajax({\r\n " +
                    "                   type: \"POST\",\r\n                    url: methodUrl,\r\n         " +
                    "           data: JSON.stringify({ drawType: \"");
                                              @__w.Write(DrawType);

            @__w.Write("\", lastWinners: winners }),\r\n                    contentType: \"application/json; " +
                    "charset=utf-8\",\r\n                    dataType: \"json\",\r\n                    succ" +
                    "ess: function (result) {\r\n\r\n                        $(\'.ajax-loader\').css(\"visib" +
                    "ility\", \"hidden\");\r\n\r\n                        if (result != null && result.d != " +
                    "null && result.d.length > 0) {\r\n\r\n                            //result.d.forEach" +
                    "(function (item) {\r\n\r\n                            //    winners.push(item);\r\n   " +
                    "                         //});\r\n\r\n                            winners = result.d" +
                    ";\r\n\r\n                            setTimeout(function () {\r\n\r\n                   " +
                    "             var table = $(\'#winnersTbl\').DataTable();\r\n                        " +
                    "        table.destroy();\r\n                                $(\'#winnersTbl\').DataT" +
                    "able({\r\n                                    data: winners,\r\n                    " +
                    "                \"bSort\": false,\r\n                                    columns: [\r" +
                    "\n                                        { \"data\": \"CustomerName\" },\r\n          " +
                    "                              { \"data\": \"AccountNumber\" },\r\n                    " +
                    "                    { \"data\": \"CreditCardNumber\" },\r\n                           " +
                    "             { \"data\": \"BranchCode\" },\r\n                                        " +
                    "{ \"data\": \"WinningAmount\" }\r\n                                    ]\r\n            " +
                    "                    });\r\n\r\n                                $(\"#loadingGif\").fade" +
                    "Out(2000);\r\n                                $(\"#winnersDiv\").fadeIn(2000);\r\n\r\n  " +
                    "                              maxWinners--;\r\n\r\n                                i" +
                    "f (maxWinners == 0) {\r\n\r\n                                    $(\'#loadingGifRow\')" +
                    ".hide();\r\n                                    $(\"#saveResultsRow\").fadeIn(2000);" +
                    "\r\n                                }\r\n                                else {\r\n   " +
                    "                                 $(\'.startDrawBtn\').fadeIn(2000);\r\n             " +
                    "                   }\r\n\r\n                            }, 3000);\r\n\r\n\r\n\r\n           " +
                    "             }\r\n\r\n                    },\r\n                    error: function (j" +
                    "qXHR, textStatus, errorThrown) {\r\n                        console.log(\'Error occ" +
                    "ured\');\r\n                        $(\'.ajax-loader\').css(\"visibility\", \"hidden\");\r" +
                    "\n\r\n                        if (jqXHR.status == 500) {\r\n                         " +
                    "   console.log(\'Internal error: \' + jqXHR.responseText);\r\n                      " +
                    "  } else {\r\n                            console.log(\'Unexpected error.\');\r\n     " +
                    "                   }\r\n                    }\r\n                });\r\n            }\r" +
                    "\n\r\n            \r\n        });\r\n\r\n\r\n\r\n    });\r\n\r\n</script>\r\n\r\n\t");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
