//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrizeDrawSystem.BillsPrizeDraw {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class BillsPrizeDraw {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(BillsPrizeDraw target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::PrizeDrawSystem.BillsPrizeDraw.BillsPrizeDraw @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h2 class=\"text-cen" +
                    "ter mt-5\">\r\n            ");
    @__w.Write(DrawType );

            @__w.Write(" Draw (Utility bills)\r\n            <br />\r\n            السحب لمرة واحدة (السحب عل" +
                    "ى الفائزين في عرض دفع الفواتير عبر تطبيق بنك نزوى)\r\n        </h2>\r\n        <hr c" +
                    "lass=\"mb-5\">\r\n\r\n        <div class=\"row\" id=\"loadingGifRow\">\r\n\r\n            <div" +
                    " class=\"col-md-3\">\r\n            </div>\r\n\r\n            <div class=\"col-md-6 text-" +
                    "center\">\r\n                <img src=\"/PublishingImages/Icons/loading.gif\" id=\"loa" +
                    "dingGif\" style=\"display: none; width: 80%;\" />\r\n                <div class=\"star" +
                    "tDrawDiv\">\r\n                    <button class=\"startDrawBtn\" onclick=\"return fal" +
                    "se;\">Start Draw بدء السحب</button>\r\n                </div>\r\n            </div>\r\n" +
                    "\r\n            <div class=\"col-md-3\">\r\n            </div>\r\n\r\n\r\n        </div>\r\n\r\n" +
                    "        <div id=\"winnersDiv\" style=\"display: none;\">\r\n            <h2 class=\"win" +
                    "nersHeading\">Winners \r\n                <br />\r\n                الفائزين\r\n       " +
                    "     </h2>\r\n            <table id=\"winnersTbl\" class=\"display\" style=\"width: 100" +
                    "%;\">\r\n                <thead>\r\n                    <tr>\r\n                       " +
                    " <th>Customer Name\r\n                            <br />\r\n                        " +
                    "    إسم العميل</th>\r\n                        <th>Account No\r\n                   " +
                    "         <br />\r\n                            رقم الحساب</th>\r\n                  " +
                    "      <th>Transaction Category</th>\r\n                        <th>Transaction Amo" +
                    "unt\r\n                            <br />\r\n                            قيمة المعام" +
                    "لة</th>\r\n                        <th>Customer</th>\r\n                        <th>" +
                    "Transaction Date</th>\r\n                        <th>Winning Amount\r\n             " +
                    "               <br />\r\n                            قيمة الجائزة</th>\r\n          " +
                    "          </tr>\r\n                </thead>\r\n            </table>\r\n            <di" +
                    "v class=\"row\" style=\"margin-top: 25px; display: none;\" id=\"saveResultsRow\">\r\n   " +
                    "             <div class=\"col text-center\">\r\n                    <button class=\"b" +
                    "tn btn-primary\" onclick=\"SaveWinnerResults(); return false;\">Save Results</butto" +
                    "n>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n</" +
                    "div>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    var maxWinners = 0;\r\n    var winn" +
                    "ers = [];\r\n\r\n    function LoadConfigurations() {\r\n\r\n        $(\'.ajax-loader\').cs" +
                    "s(\"visibility\", \"visible\");\r\n\r\n        var methodUrl = [location.protocol, \'//\'," +
                    " location.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.aspx/GetDrawButt" +
                    "onStatus\';\r\n        $.ajax({\r\n            type: \"POST\",\r\n            url: method" +
                    "Url,\r\n            data: JSON.stringify({ drawCategory: \"Bills\" }),\r\n            " +
                    "contentType: \"application/json; charset=utf-8\",\r\n            dataType: \"json\",\r\n" +
                    "            success: function (result) {\r\n\r\n                $(\'.ajax-loader\').cs" +
                    "s(\"visibility\", \"hidden\");\r\n\r\n                if (result != null && result.d != " +
                    "null) {\r\n\r\n                    if (result.d == false) {\r\n\r\n                     " +
                    "   var html = \'\';\r\n                        html += \'<div class=\"toast\" data-auto" +
                    "hide=\"false\" style=\"max-width: 100%;\">\';\r\n                        html += \'<div " +
                    "class=\"toast-header\">\';\r\n                        html += \'<strong class=\"mr-auto" +
                    " text-primary\" id=\"msgHdr\">Message</strong>\';\r\n                        html += \'" +
                    "<button type=\"button\" class=\"ml-2 mb-1 close\" data-dismiss=\"toast\">&times;</butt" +
                    "on>\';\r\n                        html += \'</div>\';\r\n                        html +" +
                    "= \'<div class=\"toast-body\" id=\"msgBody\">\';\r\n                        html += \'Ple" +
                    "ase Import Data to start draw\';\r\n                        html += \'</div>\';\r\n    " +
                    "                    html += \'</div>\';\r\n\r\n                        $(\'.startDrawDi" +
                    "v\').html(html);\r\n                        $(\'.toast\').toast(\'show\');\r\n           " +
                    "         }\r\n                    else {\r\n                        LoadDrawConfigur" +
                    "ations();\r\n                    }\r\n                }\r\n\r\n            },\r\n         " +
                    "   error: function (jqXHR, textStatus, errorThrown) {\r\n                console.l" +
                    "og(\'Error occured\');\r\n                $(\'.ajax-loader\').css(\"visibility\", \"hidde" +
                    "n\");\r\n\r\n                if (jqXHR.status == 500) {\r\n                    console." +
                    "log(\'Internal error: \' + jqXHR.responseText);\r\n                } else {\r\n       " +
                    "             console.log(\'Unexpected error.\');\r\n                }\r\n            }" +
                    "\r\n        });\r\n    }\r\n\r\n    function LoadDrawConfigurations() {\r\n\r\n        $(\'.a" +
                    "jax-loader\').css(\"visibility\", \"visible\");\r\n\r\n        var methodUrl = [location." +
                    "protocol, \'//\', location.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.a" +
                    "spx/GetMaxBillsWinners\';\r\n        $.ajax({\r\n            type: \"POST\",\r\n         " +
                    "   url: methodUrl,\r\n            data: JSON.stringify({}),\r\n            contentTy" +
                    "pe: \"application/json; charset=utf-8\",\r\n            dataType: \"json\",\r\n         " +
                    "   success: function (result) {\r\n\r\n                $(\'.ajax-loader\').css(\"visibi" +
                    "lity\", \"hidden\");\r\n                if (result != null && result.d != null) {\r\n\r\n" +
                    "                    maxWinners = result.d;\r\n                }\r\n\r\n            },\r" +
                    "\n            error: function (jqXHR, textStatus, errorThrown) {\r\n               " +
                    " console.log(\'Error occured\');\r\n                $(\'.ajax-loader\').css(\"visibilit" +
                    "y\", \"hidden\");\r\n\r\n                if (jqXHR.status == 500) {\r\n                  " +
                    "  console.log(\'Internal error: \' + jqXHR.responseText);\r\n                } else " +
                    "{\r\n                    console.log(\'Unexpected error.\');\r\n                }\r\n   " +
                    "         }\r\n        });\r\n    }\r\n\r\n    function DeleteAndArchiveData() {\r\n\r\n     " +
                    "   var methodUrl = [location.protocol, \'//\', location.host].join(\'\') + \'/_layout" +
                    "s/15/PrizeDrawSystem/WebAPI.aspx/ArchiveAndDeleteBillsData\';\r\n        $.ajax({\r\n" +
                    "            type: \"POST\",\r\n            url: methodUrl,\r\n            data: JSON.s" +
                    "tringify({}),\r\n            contentType: \"application/json; charset=utf-8\",\r\n    " +
                    "        dataType: \"json\",\r\n            success: function (result) {\r\n\r\n         " +
                    "   },\r\n            error: function (jqXHR, textStatus, errorThrown) {\r\n         " +
                    "       console.log(\'Error occured\');\r\n                if (jqXHR.status == 500) {" +
                    "\r\n                    console.log(\'Internal error: \' + jqXHR.responseText);\r\n   " +
                    "             } else {\r\n                    console.log(\'Unexpected error.\');\r\n  " +
                    "              }\r\n            }\r\n        });\r\n    }\r\n\r\n    function SaveWinnerRes" +
                    "ults() {\r\n\r\n        if (winners != null && winners.length > 0) {\r\n\r\n            " +
                    "for (var i = 0; i < winners.length; i++) {\r\n\r\n                winners[i].Transac" +
                    "tionDate = new Date(parseInt(winners[i].TransactionDate.substr(6))).toJSON();\r\n " +
                    "               delete winners[i].__type;\r\n            }\r\n\r\n            $(\'.ajax-" +
                    "loader\').css(\"visibility\", \"visible\");\r\n\r\n            var methodUrl = [location." +
                    "protocol, \'//\', location.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAPI.a" +
                    "spx/SaveBillsWinners\';\r\n            $.ajax({\r\n                type: \"POST\",\r\n   " +
                    "             url: methodUrl,\r\n                data: JSON.stringify({ drawType: \"" +
                    "");
                                          @__w.Write(DrawType);

            @__w.Write("\", allWinners: winners }),\r\n                contentType: \"application/json; chars" +
                    "et=utf-8\",\r\n                dataType: \"json\",\r\n                success: function" +
                    " (result) {\r\n\r\n                    $(\'.ajax-loader\').css(\"visibility\", \"hidden\")" +
                    ";\r\n\r\n                    console.log(result);\r\n                    if (result !=" +
                    " null && result.d != null) {\r\n\r\n                        DeleteAndArchiveData();\r" +
                    "\n\r\n                        var html = \'\';\r\n                        html += \'<div" +
                    " class=\"toast\" data-autohide=\"false\" style=\"max-width: 100%;\">\';\r\n              " +
                    "          html += \'<div class=\"toast-header\">\';\r\n                        html +=" +
                    " \'<strong class=\"mr-auto text-primary\" id=\"msgHdr\">Message</strong>\';\r\n         " +
                    "               html += \'<button type=\"button\" class=\"ml-2 mb-1 close\" data-dismi" +
                    "ss=\"toast\">&times;</button>\';\r\n                        html += \'</div>\';\r\n      " +
                    "                  html += \'<div class=\"toast-body\" id=\"msgBody\">\';\r\n            " +
                    "            html += \'Winners data is saved successfully\';\r\n                     " +
                    "   html += \'</div>\';\r\n                        html += \'</div>\';\r\n\r\n             " +
                    "           $(\'.startDrawDiv\').html(html);\r\n                        $(\'.toast\').t" +
                    "oast(\'show\');\r\n                        $(\'#loadingGifRow\').show();\r\n            " +
                    "            $(\'#winnersDiv\').html(\'\');\r\n                    }\r\n\r\n               " +
                    " },\r\n                error: function (jqXHR, textStatus, errorThrown) {\r\n       " +
                    "             console.log(\'Error occured\');\r\n                    $(\'.ajax-loader\'" +
                    ").css(\"visibility\", \"hidden\");\r\n\r\n                    if (jqXHR.status == 500) {" +
                    "\r\n                        console.log(\'Internal error: \' + jqXHR.responseText);\r" +
                    "\n                    } else {\r\n                        console.log(\'Unexpected e" +
                    "rror.\');\r\n                    }\r\n                }\r\n            });\r\n        }\r\n" +
                    "    }\r\n\r\n    $(function () {\r\n\r\n\r\n        LoadConfigurations();\r\n\r\n        $(\'.s" +
                    "tartDrawBtn\').click(function () {\r\n\r\n            $(\'.startDrawBtn\').hide();\r\n   " +
                    "         $(\"#loadingGif\").fadeIn(2000);\r\n\r\n\r\n            var methodUrl = [locati" +
                    "on.protocol, \'//\', location.host].join(\'\') + \'/_layouts/15/PrizeDrawSystem/WebAP" +
                    "I.aspx/\';\r\n\r\n            if (maxWinners > 5) {\r\n\r\n                methodUrl += \"" +
                    "GetBillsAllWinners\";\r\n\r\n                $(\'.ajax-loader\').css(\"visibility\", \"vis" +
                    "ible\");\r\n\r\n                $.ajax({\r\n                    type: \"POST\",\r\n        " +
                    "            url: methodUrl,\r\n                    data: JSON.stringify({ drawType" +
                    ": \"");
                                              @__w.Write(DrawType);

            @__w.Write("\" }),\r\n                    contentType: \"application/json; charset=utf-8\",\r\n     " +
                    "               dataType: \"json\",\r\n                    success: function (result)" +
                    " {\r\n\r\n                        $(\'.ajax-loader\').css(\"visibility\", \"hidden\");\r\n\r\n" +
                    "                        if (result != null && result.d != null && result.d.lengt" +
                    "h > 0) {\r\n\r\n                            winners = result.d;\r\n\r\n                 " +
                    "           setTimeout(function () {\r\n\r\n                                $(\'#winne" +
                    "rsTbl\').DataTable({\r\n                                    data: winners,\r\n       " +
                    "                             \"bSort\": false,\r\n                                  " +
                    "  columns: [\r\n                                        { \"data\": \"CustomerName\" }" +
                    ",\r\n                                        { \"data\": \"AccountNumber\" },\r\n       " +
                    "                                 { \"data\": \"TransactionCategory\" },\r\n           " +
                    "                             { \"data\": \"TransactionAmount\" },\r\n                 " +
                    "                       { \"data\": \"Customer\" },\r\n                                " +
                    "        { \"data\": \"TransactionDateStr\" },\r\n                                     " +
                    "   { \"data\": \"WinningAmount\" }\r\n                                    ]\r\n         " +
                    "                       });\r\n\r\n                                $(\"#loadingGif\").f" +
                    "adeOut(2000);\r\n                                $(\'#loadingGifRow\').hide();\r\n    " +
                    "                            $(\"#winnersDiv\").fadeIn(2000);\r\n                    " +
                    "            $(\"#saveResultsRow\").fadeIn(2000);\r\n\r\n                            }," +
                    " 3000);\r\n\r\n\r\n\r\n                        }\r\n\r\n                    },\r\n            " +
                    "        error: function (jqXHR, textStatus, errorThrown) {\r\n                    " +
                    "    console.log(\'Error occured\');\r\n                        $(\'.ajax-loader\').css" +
                    "(\"visibility\", \"hidden\");\r\n\r\n                        if (jqXHR.status == 500) {\r" +
                    "\n                            console.log(\'Internal error: \' + jqXHR.responseText" +
                    ");\r\n                        } else {\r\n                            console.log(\'U" +
                    "nexpected error.\');\r\n                        }\r\n                    }\r\n         " +
                    "       });\r\n            }\r\n            else {\r\n\r\n                methodUrl += \"G" +
                    "etBillsSingleWinner\";\r\n\r\n                if (winners != null && winners.length >" +
                    " 0) {\r\n\r\n                    for (var i = 0; i < winners.length; i++) {\r\n\r\n     " +
                    "                   winners[i].TransactionDate = new Date(parseInt(winners[i].Tra" +
                    "nsactionDate.substr(6))).toJSON();\r\n                        delete winners[i].__" +
                    "type;\r\n                    }\r\n                }\r\n\r\n                $(\'.ajax-load" +
                    "er\').css(\"visibility\", \"visible\");\r\n\r\n                $.ajax({\r\n                " +
                    "    type: \"POST\",\r\n                    url: methodUrl,\r\n                    data" +
                    ": JSON.stringify({ drawType: \"");
                                              @__w.Write(DrawType);

            @__w.Write("\", lastWinners: winners }),\r\n                    contentType: \"application/json; " +
                    "charset=utf-8\",\r\n                    dataType: \"json\",\r\n                    succ" +
                    "ess: function (result) {\r\n\r\n                        $(\'.ajax-loader\').css(\"visib" +
                    "ility\", \"hidden\");\r\n\r\n                        if (result != null && result.d != " +
                    "null && result.d.length > 0) {\r\n\r\n                            //result.d.forEach" +
                    "(function (item) {\r\n\r\n                            //    winners.push(item);\r\n   " +
                    "                         //});\r\n\r\n                            winners = result.d" +
                    ";\r\n\r\n                            setTimeout(function () {\r\n\r\n                   " +
                    "             var table = $(\'#winnersTbl\').DataTable();\r\n                        " +
                    "        table.destroy();\r\n                                $(\'#winnersTbl\').DataT" +
                    "able({\r\n                                    data: winners,\r\n                    " +
                    "                \"bSort\": false,\r\n                                    columns: [\r" +
                    "\n                                        { \"data\": \"CustomerName\" },\r\n          " +
                    "                              { \"data\": \"AccountNumber\" },\r\n                    " +
                    "                    { \"data\": \"TransactionCategory\" },\r\n                        " +
                    "                { \"data\": \"TransactionAmount\" },\r\n                              " +
                    "          { \"data\": \"Customer\" },\r\n                                        { \"da" +
                    "ta\": \"TransactionDateStr\" },\r\n                                        { \"data\": " +
                    "\"WinningAmount\" }\r\n                                    ]\r\n                      " +
                    "          });\r\n\r\n                                $(\"#loadingGif\").fadeOut(2000);" +
                    "\r\n                                $(\"#winnersDiv\").fadeIn(2000);\r\n\r\n            " +
                    "                    maxWinners--;\r\n\r\n                                if (maxWinn" +
                    "ers == 0) {\r\n\r\n                                    $(\'#loadingGifRow\').hide();\r\n" +
                    "                                    $(\"#saveResultsRow\").fadeIn(2000);\r\n        " +
                    "                        }\r\n                                else {\r\n             " +
                    "                       $(\'.startDrawBtn\').fadeIn(2000);\r\n                       " +
                    "         }\r\n\r\n                            }, 3000);\r\n\r\n\r\n\r\n                     " +
                    "   }\r\n\r\n                    },\r\n                    error: function (jqXHR, text" +
                    "Status, errorThrown) {\r\n                        console.log(\'Error occured\');\r\n " +
                    "                       $(\'.ajax-loader\').css(\"visibility\", \"hidden\");\r\n\r\n       " +
                    "                 if (jqXHR.status == 500) {\r\n                            console" +
                    ".log(\'Internal error: \' + jqXHR.responseText);\r\n                        } else {" +
                    "\r\n                            console.log(\'Unexpected error.\');\r\n               " +
                    "         }\r\n                    }\r\n                });\r\n            }\r\n\r\n\r\n     " +
                    "   });\r\n\r\n\r\n\r\n    });\r\n\r\n</script>\r\n\r\n");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
